/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author USER
 */
public class PenampilGambarDenganButtonGUI extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarDenganButtonGUI
     */
    public PenampilGambarDenganButtonGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelbtn = new javax.swing.JPanel();
        btnmoon = new javax.swing.JButton();
        btnneverland = new javax.swing.JButton();
        btndragon = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        panelfoto = new javax.swing.JPanel();
        lblmoon = new javax.swing.JLabel();
        lblneverland = new javax.swing.JLabel();
        lbldragon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelbtn.setBackground(new java.awt.Color(51, 204, 255));

        btnmoon.setText("Moon");
        btnmoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoonActionPerformed(evt);
            }
        });
        panelbtn.add(btnmoon);

        btnneverland.setText("Forever Neverland");
        btnneverland.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnneverlandActionPerformed(evt);
            }
        });
        panelbtn.add(btnneverland);

        btndragon.setText("The Secret Dragon");
        btndragon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndragonActionPerformed(evt);
            }
        });
        panelbtn.add(btndragon);

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        panelbtn.add(btnexit);

        getContentPane().add(panelbtn, java.awt.BorderLayout.PAGE_START);

        panelfoto.setLayout(new java.awt.CardLayout());

        lblmoon.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\Rekomendasi Buku Bacaan Buat Remaja _ Life and Travel Journal.jpeg")); // NOI18N
        panelfoto.add(lblmoon, "0");

        lblneverland.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\Cover Reveal_ Forever Neverland by Susan Adrian.jpeg")); // NOI18N
        panelfoto.add(lblneverland, "1");

        lbldragon.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Downloads\\24 must-read books for 9-12-year-olds.jpeg")); // NOI18N
        panelfoto.add(lbldragon, "2");

        getContentPane().add(panelfoto, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoonActionPerformed
        CardLayout cl = (CardLayout)(panelfoto.getLayout());
        cl.show(panelfoto,"0");
    }//GEN-LAST:event_btnmoonActionPerformed

    private void btnneverlandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnneverlandActionPerformed
        CardLayout cl = (CardLayout)(panelfoto.getLayout());
        cl.show(panelfoto,"1");
    }//GEN-LAST:event_btnneverlandActionPerformed

    private void btndragonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndragonActionPerformed
        CardLayout cl = (CardLayout)(panelfoto.getLayout());
        cl.show(panelfoto,"2");
    }//GEN-LAST:event_btndragonActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PenampilGambarDenganButtonGUI fullFrame = new PenampilGambarDenganButtonGUI();
                GraphicsDevice device =
                       GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndragon;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnmoon;
    private javax.swing.JButton btnneverland;
    private javax.swing.JLabel lbldragon;
    private javax.swing.JLabel lblmoon;
    private javax.swing.JLabel lblneverland;
    private javax.swing.JPanel panelbtn;
    private javax.swing.JPanel panelfoto;
    // End of variables declaration//GEN-END:variables
}
